### ISSUE TITLE
is beautifulsoup 4.1.9 a fixed requirement?

### ISSUE THREAD

**Issue by JensTimmerman** [Te-k/pycrtsh#12]
currently this package relies on beautifulsoup4==4.9.1

this breaks my tool which relies on another dependency that relies on beautifulsoup4>=4.9.3

is the 4.9.1 a hard dependency?

**Comment by Te-k** [comment]
Beautiful soup evolves regularly, I cannot guarantee that the tool will work on more recent versions of BS, so I prefer to keep it that way, is there a better alternative ?

**Comment by Te-k** [comment]
Actually I forgot I had tests, I tested with the last BS and it works so I upgraded the BS version, you can use pycrtsh 0.3.7 and it should be good

**Comment by JensTimmerman** [comment]
Thank you for the version bump, I had already made this change locally and indeed I am not really seeing any issues :)
