### ISSUE TITLE
Table rows are not fixed when searching for certificates using SHA1 and SHA256 queries 

### ISSUE THREAD

**Issue by jimmy-ly00** [Te-k/pycrtsh#14]
When using certsh with SHA1 and SHA256, they are not fixed at certain fields. The problem is in:

api.py
```
        cert['sha256'] = lines1[4].find("th", text="SHA-256").find_next_sibling("td").text
        cert["sha1"] = lines1[4].find("th", text="SHA-1").find_next_sibling("td").text
```

For example, see the following:

`https://crt.sh/?q=28F97816197AFF182518AA44FEC1A0CE5CB64C8A -> cert["sha1"] = lines1[6].find("th", text="SHA-1").find_next_sibling("td").text`

`https://crt.sh/?q=27D5BBE04301E1604839708D172CF09296ED9033 -> cert["sha1"] = lines1[5].find("th", text="SHA-1").find_next_sibling("td").text`

I believe there needs to be a better way to search for these rows. I don't have a great solution to this, but as a temporary solution, I can do a couple of try/except, I'm certain there is a cleaner/programmatic way to do it instead

```
    try:
        print(lines1[6].find("th", text="SHA-1").find_next_sibling("td").text)
    except Exception:
        pass
    try:
        print(lines1[5].find("th", text="SHA-1").find_next_sibling("td").text)
    except Exception:
        pass
    try:
        print(lines1[4].find("th", text="SHA-1").find_next_sibling("td").text)
    except Exception:
        pass
```

**Comment by Te-k** [comment]
Hi, indeed, I should have fixed it with the last commit, can you check that it works for you?
If it does, I'll push a new version with it.

Thanks

**Comment by jimmy-ly00** [comment]
I tested it on a bunch of SHA256 hashes, it looks good, thanks for the quick fix
