### ISSUE TITLE
crashes when invalid inputs are supplied instead of y/n

### ISSUE THREAD

**Issue by ranlo** [Te-k/pycrtsh#16]
When I simply press Enter instead of y/n, I get

`Extract domains with the same IP? y/n:
Traceback (most recent call last):
  File "webosint.py", line 322, in <module>
    main()
  File "webosint.py", line 310, in main
    rev_ip()
TypeError: rev_ip() missing 2 required positional arguments: 'domain_ip' and 'domain'`

Code should have a default (Y for passive operations, N for active) instead of crashing

**Comment by Te-k** [comment]
Hi, 

I am not sure which tool you used, but it wasn't pycrtsh as there is no file called `webosint.py`. Could you share the command you used?

Thanks

**Comment by ranlo** [comment]
And that's what happens when you're testing multiple tools in parallel. My bad. Apologies! :)
