### ISSUE TITLE
legacy install failure 

### ISSUE THREAD

**Issue by dc-sf** [Te-k/pycrtsh#17]
Failing to get pycrtsh cli to work. 
Followed installation instructions and unable to get cli to work as outlined in README

1st option: created conda venv called pycrtsh
Activated pycrtsh conda venv and then performed pip install pycrtsh within pycrtsh venv
During installation: 
<img width="702" alt="Screenshot 2023-02-09 at 15 52 06" src="https://user-images.githubusercontent.com/122648336/217964866-ff8564d2-e247-4a1b-81d2-6346b186362e.png">

2nd option: cloned pycrtsh.git locallly. 
`pip install .`

Both options resulted in failures and unable to run certsh from command line.

**Comment by Te-k** [comment]
Hi, indeed you first need to install [lxml](https://lxml.de/installation.html) dependencies, on Ubuntu/Debian : `https://lxml.de/installation.html`.

I have updated the README to add this, let me know if it fixes your problem
