### ISSUE TITLE
Field name changes

### ISSUE THREAD

**Issue by tlansec** [Te-k/pycrtsh#5]
Hello,

There have been some fieldname changes at crtsh which means the lib needs changing, specifically in the api.search(0 method it's expecting:

min_cert_id 
min_entry_timestamp

these are now:

id
entry_timestamp

Cheers,
Tom

**Comment by tlansec** [comment]
Example query url and output to illustrate:

https://crt.sh/?q=okta.com.%25&output=json

`{"issuer_ca_id":24,"issuer_name":"C=US, ST=Arizona, L=Scottsdale, O=\"GoDaddy.com, Inc.\", OU=http://certificates.godaddy.com/repository, CN=Go Daddy Secure Certification Authority, serialNumber=07969287","name_value":"*.okta.com\nokta.com","id":2376751455,"entry_timestamp":"2020-01-25T18:14:07.305","not_before":"2010-04-08T19:58:38","not_after":"2011-04-08T19:58:38"}`

**Comment by Te-k** [comment]
Hi, 
Thanks, crt.sh indeed changed their JSON format (and HTML output too). I have pushed a commit that should fix that, can you check if it works for you ? If it does, I will update the pypi package

**Comment by ehananel** [comment]
i checked it ... managed to receive expected responses.
i replaced min_cert_id & min_entry_timestamp with id & entry_timestamp.

can you update the package ?

**Comment by Te-k** [comment]
Here it is https://pypi.org/project/pycrtsh/
