### ISSUE TITLE
SHA-256 and SHA-1 is now displayed in the same line

### ISSUE THREAD

**Issue by Shinzu** [Te-k/pycrtsh#6]
with https://github.com/crtsh/certwatch_db/commit/5e310cb7568ebf75113dcc001c2b06f9517583ec sha-256 and sha-1 fingerprint is displayed on the same line , which breaks the get function in https://github.com/Te-k/pycrtsh/blob/master/pycrtsh/api.py#L78

**Comment by Shinzu** [comment]
in my fork i fixed it with https://github.com/Shinzu/pycrtsh/commit/515eec2b5f3241c977af4d9b06b9860487971435

**Comment by Te-k** [comment]
Great ! Thanks for catching that and fixing it
