### ISSUE TITLE
TypeError: Parser must be a string or character stream, not NoneType

### ISSUE THREAD

**Issue by jegan019** [Te-k/pycrtsh#7]
Hi, I am trying to use this tool to retrieve the subject information from certificates that are issued to an organization.
This tool works when I run `certsh domain "Open Access Technology International"`
However this tool fails when I run `certsh domain "National Center for Digital Certification"` apparently an error concerning the date parsing is causing the failure. This is probably due to the lack of any values present to parse. Hence I think you should check for null values before going ahead with the parsing.

![Capture](https://user-images.githubusercontent.com/16530101/87860812-7c476400-c90e-11ea-87d7-9dce763a91b1.PNG)

**Comment by jegan019** [comment]
Upon looking at the website, I noticed that the error is due to a few entries missing entry timestamps. 

![Capture](https://user-images.githubusercontent.com/16530101/87861192-ef9ea500-c911-11ea-8e83-446b515a22ca.PNG)

**Comment by Te-k** [comment]
Do you still have this problem?
It works on my computer with the last commit.

**Comment by jegan019** [comment]
> Do you still have this problem?
> It works on my computer with the last commit.

I mitigated the issue by manually adding checks for empty timestamps. This works now.

**Comment by Te-k** [comment]
Ok, thanks, feel free to reopen it if it still is an issue
