### ISSUE TITLE
id =1,it dosn't work,i think ur parser has something wrong

### ISSUE THREAD

**Issue by yangjinhao1234** [Te-k/pycrtsh#8]
i think the response.html is not like what u want.
so ur code raise the error,maybe bs4 error? i don't know .can u check it ?

**Comment by yangjinhao1234** [comment]
i try to parse it using xpath & re, i want turn the raw data to the dict ,so i can use it in json type, do u hava some idea? 
thank u

**Comment by Te-k** [comment]
I am not sure I get what is the problem you encounter, can you share some code that create the issue? What pycrtsh version are you using?
